# Generated by Django 3.2.6 on 2021-10-24 14:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioPrestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=150)),
                ('duracionTurno', models.IntegerField(default=30)),
                ('ciudad', models.CharField(blank=True, choices=[('Rafaela', 'Rafaela'), ('Santa Fe', 'Santa Fe'), ('Rosario', 'Rosario')], default='Rafaela', max_length=20, null=True, verbose_name='Ciudad')),
                ('inicioJornada', models.TimeField(blank=True, default='08:00:00', verbose_name='Inicio de Jornada')),
                ('finJornada', models.TimeField(blank=True, default='17:00:00', verbose_name='Fin de Jornada')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.categoria')),
                ('diasAtencion', models.ManyToManyField(to='sitio.Days')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(blank=True, max_length=255)),
                ('key_expires', models.DateTimeField(default=datetime.date(2021, 10, 24))),
                ('tipo', models.CharField(choices=[('cliente', 'CLIENTE'), ('profesional', 'PROFESIONAL')], default='cliente', max_length=16, null=True, verbose_name='Tipo usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=datetime.datetime(2021, 10, 24, 11, 31, 52, 435370), verbose_name='Fecha inicio')),
                ('horario', models.TimeField(blank=True, default='08:00:00', verbose_name='Horario')),
                ('fecha_fin', models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 24, 11, 31, 52, 435370), null=True, verbose_name='Fecha Fin')),
                ('confirmado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.servicioprestado')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='servicioprestado',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.subcategoria'),
        ),
    ]
