# Generated by Django 3.2.6 on 2021-08-31 20:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_auto_20210824_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'CLIENTE'), ('profesional', 'PROFESIONAL')], default='cliente', max_length=16, null=True, verbose_name='Tipo usuario'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2021, 8, 31)),
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioPrestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.categoria')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.userprofile')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.subcategoria')),
            ],
        ),
    ]
