# Generated by Django 3.2.6 on 2021-10-25 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_auto_20211025_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 25, 17, 58, 2, 925472), null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 17, 58, 2, 925472), verbose_name='Fecha inicio'),
        ),
    ]
