# Generated by Django 3.2.6 on 2021-10-25 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_auto_20211025_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 25, 18, 4, 16, 182330), null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 18, 4, 16, 182330), verbose_name='Fecha inicio'),
        ),
    ]
