# Generated by Django 3.2.6 on 2021-09-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_auto_20210907_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nombre',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
