# Generated by Django 3.2.6 on 2021-09-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_auto_20210907_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
