# Generated by Django 3.2.6 on 2021-09-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_auto_20210907_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioprestado',
            name='descripcion',
            field=models.TextField(max_length=255),
        ),
    ]
