# Generated by Django 3.2.6 on 2021-09-18 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_alter_servicioprestado_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2021, 9, 18)),
        ),
    ]
