# Generated by Django 3.2.6 on 2021-09-28 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0011_auto_20210928_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioprestado',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.categoria'),
        ),
        migrations.AlterField(
            model_name='servicioprestado',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.subcategoria'),
        ),
    ]
