# Generated by Django 3.2.6 on 2021-10-12 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0013_alter_userprofile_key_expires'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2021, 10, 12)),
        ),
        migrations.AddField(
            model_name='servicioprestado',
            name='diasAtencion',
            field=models.ManyToManyField(to='sitio.Days'),
        ),
    ]
