# Generated by Django 3.2.6 on 2021-10-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0015_auto_20211014_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioprestado',
            name='duracionTurno',
            field=models.IntegerField(default=30),
        ),
    ]
