# Generated by Django 3.2.6 on 2021-10-21 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0016_servicioprestado_duracionturno'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioprestado',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('Rafaela', 'Rafaela'), ('Santa Fe', 'Santa Fe'), ('Rosario', 'Rosario')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2021, 10, 20)),
        ),
    ]
