# Generated by Django 3.2.6 on 2021-10-22 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0017_auto_20211020_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioprestado',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('Rafaela', 'Rafaela'), ('Santa Fe', 'Santa Fe'), ('Rosario', 'Rosario')], default='Rafaela', max_length=20, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2021, 10, 22)),
        ),
    ]
