# Generated by Django 3.2.6 on 2021-10-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0024_alter_servicioprestado_finjornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioprestado',
            name='finJornada',
            field=models.TimeField(blank=True, default='17:00:00', verbose_name='Fin de Jornada'),
        ),
    ]
