# Generated by Django 3.2.6 on 2021-10-23 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0025_alter_servicioprestado_finjornada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='fecha_fin',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2021, 10, 23)),
        ),
    ]
