# Generated by Django 3.2.6 on 2021-10-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0026_auto_20211023_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='horario',
            field=models.TimeField(blank=True, default='08:00:00', verbose_name='Horario'),
        ),
    ]
