# Generated by Django 3.2.6 on 2021-10-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0027_turno_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioprestado',
            name='finJornada',
            field=models.DateTimeField(blank=True, default='2021-01-01T17:00:00', verbose_name='Fin de Jornada'),
        ),
        migrations.AlterField(
            model_name='servicioprestado',
            name='inicioJornada',
            field=models.DateTimeField(blank=True, default='2021-01-01T08:00:00', verbose_name='Inicio de Jornada'),
        ),
    ]
