# Generated by Django 3.2.6 on 2021-10-23 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0029_auto_20211023_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 16, 56, 47, 841641), verbose_name='Fecha inicio'),
        ),
    ]
