# Generated by Django 3.2.6 on 2021-10-23 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0031_auto_20211023_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 23, 20, 33, 55, 192099), null=True, verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 20, 33, 55, 192099), verbose_name='Fecha inicio'),
        ),
    ]
