# Generated by Django 3.2.6 on 2021-10-24 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0031_auto_20211023_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 10, 55, 7, 225070), verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2021, 10, 24)),
        ),
    ]
