# Generated by Django 3.2.6 on 2021-10-24 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0033_auto_20211023_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 24, 10, 20, 6, 183774), null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 10, 20, 6, 183774), verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2021, 10, 24)),
        ),
    ]
