# Generated by Django 3.2.6 on 2021-10-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0032_auto_20211024_1055'),
        ('sitio', '0034_auto_20211024_1020'),
    ]

    operations = [
    ]
