# Generated by Django 3.2.6 on 2021-10-24 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0035_merge_0032_auto_20211024_1055_0034_auto_20211024_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 24, 11, 19, 28, 52701), null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 11, 19, 28, 52701), verbose_name='Fecha inicio'),
        ),
    ]
